package neww;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.atomic.AtomicReference;

public class replaceCheck {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		AtomicReference<String> sql = new AtomicReference<>("SELECT * FROM  (SELECT * FROM (SELECT (SELECT REPLACE((REPLACE((ARRAY_TO_STRING((SELECT ARRAY_AGG(SORTING)  FROM (SELECT UNNEST( STRING_TO_ARRAY( (CONCAT_WS (',',(CASE WHEN TRIM(MAKER)='' THEN NULL ELSE MAKER END),(CASE WHEN TRIM(CHECKER)='' THEN NULL ELSE CHECKER END),(CASE WHEN TRIM(DETINV_MAKER)='' THEN NULL ELSE DETINV_MAKER END),(CASE WHEN TRIM(DETINV_CHECKER)='' THEN NULL ELSE DETINV_CHECKER END) ) ),',' ) )  ORDER BY 1) SORTING ), ',')),'(','')),')','')) MAILGROUP,ALERT_DATE::DATE ALERT_DATE,ALERT_ID ALERT_ID,DETINV_DATE_OF_INITIATION DETINV_DATE_OF_INITIATION,ALERT_NAME ALERT_NAME,DETINV_CRO_APPROVAL_DATE DETINV_CRO_APPROVAL_DATE,'STR-REMINDER' MAILTYPE FROM CM_ALERTS WHERE ALERT_ID IN (SELECT ALERT_ID FROM (SELECT ALERT_ID,COUNT(1) AS NOOFDAYS FROM S_NSE_CALENDAR A,CM_ALERTS B WHERE DETINV_CRO_APPROVAL_DATE IS NOT NULL AND DETINV_STR_FILLING_DATE IS NULL AND  DAY BETWEEN DETINV_CRO_APPROVAL_DATE::DATE AND (:BUSSDATE)::DATE GROUP BY 1) A WHERE A.NOOFDAYS <= (4)) )A :SPECIALWHERE UNION ALL SELECT (SELECT REPLACE((REPLACE((ARRAY_TO_STRING((SELECT ARRAY_AGG(SORTING)  FROM ( SELECT UNNEST( STRING_TO_ARRAY( (CONCAT_WS (',',(CASE WHEN TRIM(MAKER)='' THEN NULL ELSE MAKER END),(CASE WHEN TRIM(CHECKER)='' THEN NULL ELSE CHECKER END),(CASE WHEN TRIM(DETINV_MAKER)='' THEN NULL ELSE DETINV_MAKER END),(CASE WHEN TRIM(DETINV_CHECKER)='' THEN NULL ELSE DETINV_CHECKER END) ) ),',' ) )  ORDER BY 1) SORTING ), ',')),'(','')),')','' ) ) MAILGROUP,ALERT_DATE::DATE,ALERT_ID,DETINV_DATE_OF_INITIATION,ALERT_NAME,DETINV_CRO_APPROVAL_DATE,'STR-ESCLATION' MAILTYPE FROM CM_ALERTS WHERE ALERT_ID IN (SELECT ALERT_ID FROM (SELECT ALERT_ID,COUNT(1) AS NOOFDAYS FROM S_NSE_CALENDAR A,CM_ALERTS B WHERE  DETINV_CRO_APPROVAL_DATE IS NOT NULL AND DETINV_STR_FILLING_DATE IS NULL AND DAY BETWEEN DETINV_CRO_APPROVAL_DATE::DATE AND (:BUSSDATE)::DATE GROUP BY 1) A WHERE A.NOOFDAYS > (4) ) ) A :SPECIALOUTERWHERE");
Map<String, String > criteria = new HashMap<String, String>();
criteria.put("SPECIALOUTERWHERE", " where 1=0");
criteria.put("BUSSDATE", " 2023-08-01");
criteria.put("SPECIALWHERE", " where 1=1");

criteria.forEach(((t, u) -> {
	// sql = new String();
	sql.set( (sql.get()).replaceAll(":"+t, u));
}));
System.out.println(sql.get());
	}

}
